# This is default jargon that you can use. Feel free to change it. See: https://boogi.netlify.app/editing/rich_content/abbreviations
'AGPIAL':
  name: AGPIAL
  long_name: AGPIAL
  description: A good pilot, programmer, person is always learning. A mix of technology, aviation, aduiobooks avideo books for learning and education.
